# Generated by Django 3.1.1 on 2021-09-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
            ],
            options={
                'verbose_name': '食べ物',
                'verbose_name_plural': '食べ物一覧',
                'db_table': 'excel',
            },
        ),
    ]
