# Generated by Django 3.1.1 on 2021-09-23 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BI_tool', '0002_littering_prefectures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='littering',
            old_name='Bottles',
            new_name='bottles',
        ),
        migrations.RenameField(
            model_name='littering',
            old_name='Can',
            new_name='can',
        ),
        migrations.RenameField(
            model_name='littering',
            old_name='Collection_date',
            new_name='collection_date',
        ),
        migrations.RenameField(
            model_name='littering',
            old_name='Prefectures',
            new_name='prefectures',
        ),
        migrations.RenameField(
            model_name='littering',
            old_name='Tobacco',
            new_name='tobacco',
        ),
    ]
